### ISSUE TITLE
Encryption keys are extractable

### ISSUE THREAD

**Issue by meehow** [f-secure-foundry/interlock#50]
This code is using very weird security concept. It assumes that device supports hardware encryption, but it's used just to construct encryption key and uses it later in software layer. `unix.ALG_OP_DECRYPT` mode is not even used in the code (just `unix.ALG_OP_ENCRYPT`). The security features of required hardware are underutilized and whole encryption key is as good as I would use serial number of a device without hardware encryption.

**Comment by andrejro** [comment]
The encryption key is derived from user provided passphrase and wrapped with the hardware device specific key.
The wrapping uses only `unix.ALG_OP_ENCRYPT`. There is no `unix.ALG_OP_DECRYPT` as the key is derived from user passphrase.

**Comment by meehow** [comment]
Key is wrapped, derived or whatever, but at the end only software encryption/decryption takes place. If we [save the key](https://github.com/f-secure-foundry/interlock/blob/15c9be9b6ebb43115e66638b8a297d2e076ef1bb/internal/dcp_linux.go#L148), we will be able to decrypt all the data in any given point in time on any type of hardware.

**Comment by abarisani** [comment]
The claim that we make is the following (quoting the README):

"The HSM support allows symmetric ciphering using device specific secret keys, allowing to uniquely tie derived keys to the specific hardware unit being used. An HSM specific AES-OFB based symmetric cipher is exposed, with keys derived from the user password as well as device specific secret."

There is no claim that the key is protected and used exclusively within hardware and the same applies to the LUKS key which is inevitably held in memory by Linux.

The README mentions twice "hardware key" without too much context, I can understand that this might be misleading and I am happy to change the wording of that if this is what this issue is about.

When you say "save the key" here it means compromising the environment or software running on the device, and the way this project is designed is not intended to protect against that as, again, we never make a claim that we do encryption and key protection exclusively within hardware/HSM.

Rather we clearly document that this project is an interface to LUKS and that the HSM is used to aid device specific derivation, nothing more.

**Comment by meehow** [comment]
I understand that there is no claim that key is protected, just what's the purpose of requiring hardware encryption, when it's used just to derive a key?
I understand that modifications, which would allow key extraction (especially in secure boot environment), are not easy to be deployed unnoticed and must be done by holder of signing keys, but if it happens once, all future data can be decrypted on other device.

I think complexity of introducing hardware encryption and decryption (instead of working with derived key) is relatively low comparing to benefits it provides and amount of work which already has been done in this repo.

I understand that you don't want to break backward compatibility of this tool with data people already encrypted, so changing README would be better than nothing. [mxs-dcp](https://github.com/f-secure-foundry/mxs-dcp/issues/5) doesn't have this constrain, so maybe let's keep this issue opened there, otherwise this code will be copied by people who are looking for example implementation of hardware key encryption.

**Comment by abarisani** [comment]
We don't require hardware encryption, using an HSM is an optional feature.

It's a diversification feature (based on a secret non-public value), nothing more and nothing less.

**Comment by abarisani** [comment]
I propose this change to address any potentially misleading statement:

```
diff --git a/README.md b/README.md
index 8192483..fc1a7d9 100644
--- a/README.md
+++ b/README.md
@@ -18,9 +18,7 @@ individual files.
 ![INTERLOCK screenshot](https://github.com/f-secure-foundry/interlock/wiki/images/interlock.png)
 
 A command line mode is available to execute selected operations locally,
-without the web interface. This is primarily intended to aid
-encryption/decryption operation with hardware keys, using HSM support on
-embedded firmwares.
+without the web interface.
 
 Authors
 =======
@@ -50,7 +48,7 @@ application server implementing the protocol specified in the API document.
 
 A command line mode is available to execute selected operations locally,
 without the web interface. This is primarily intended to aid
-encryption/decryption operation with hardware keys, using HSM support on
+encryption/decryption operation with key derivation using HSM support on
 embedded firmwares.
 
 The JSON application server is written in golang. The client HTML/Javascript
```

**Comment by abarisani** [comment]
By the way, if you are interested in using the DCP on the USB armory Mk II with key protection please refer to our [TamaGo](https://github.com/f-secure-foundry/tamago) framework and the [DCP API](https://pkg.go.dev/github.com/f-secure-foundry/tamago/soc/imx6/dcp).

**Comment by meehow** [comment]
TamaGo would be a good alternative for my project, but at the moment it doesn't compile without CGO because of libusb dependency. Is there USB hid support for TamaGo?

**Comment by abarisani** [comment]
Yes, we have HID support. In fact [GoKey](https://github.com/f-secure-foundry/GoKey) uses it for its [U2F](https://github.com/f-secure-foundry/GoKey/blob/master/internal/u2f/token.go) implementation.
